services:
  postgres:
    image: postgres:16-alpine
    container_name: lightlist-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lightlist_user
      POSTGRES_PASSWORD: lightlist_password
      POSTGRES_DB: lightlist_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lightlist_user -d lightlist_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: